[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_source = '''
let g:coc_global_extensions = [
      \ 'coc-lists',
      \ 'coc-emoji',
      \ 'coc-diagnostic',
      \ 'coc-prettier',
      \ 'coc-pairs',
      \ 'coc-git',
      \ 'coc-json',
      \ 'coc-yaml',
      \ 'coc-vimlsp',
      \ 'coc-xml',
      \ 'coc-calc',
      \ 'coc-cmake',
      \ 'coc-ci',
      \ 'coc-tsserver',
      \ 'coc-vetur',
      \ 'coc-eslint',
      \ 'coc-css', 
      \ 'coc-emmet',
      \ 'coc-stylelint',
      \ 'coc-java',
      \ 'coc-jedi',
      \ 'coc-rls',
      \ 'coc-docker',
      \ 'coc-sh',
      \]

let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'

command! -nargs=0 Format :call CocAction('format')
command! -nargs=0 OR     :call CocAction('runCommand', 'editor.action.organizeImport')
command! -nargs=? Fold   :call CocAction('fold', <f-args>)

" coc-git
highlight DiffAdd ctermfg=22 guifg=#006000 ctermbg=NONE guibg=NONE
highlight DiffChange ctermfg=58 guifg=#5F6000 ctermbg=NONE guibg=NONE
highlight DiffDelete ctermfg=52 guifg=#600000 ctermbg=NONE guibg=NONE
highlight default CocHighlightText  guibg=#725972 ctermbg=96
" virtual text highlight
highlight! CocCodeLens guifg=#606060 ctermfg=60
" error/warning/info/hit sign
highlight! CocErrorSign ctermfg=Red guifg=#ea6962
highlight! CocWarningSign ctermfg=Yellow guifg=#e3a84e
highlight! CocInfoSign ctermfg=Blue guifg=#7dae9b
highlight! CocHintSign ctermfg=Blue guifg=#7dae9b
" diff sign highlight groups
highlight GitAddHi    guifg=#b8bb26 ctermfg=40
highlight GitModifyHi guifg=#83a598 ctermfg=33
highlight GitDeleteHi guifg=#f3423a ctermfg=196
highlight CocCursorRange guibg=#b16286 guifg=#ebdbb2
" highlight text color
highlight! CocHighlightText  guibg=#054c20 ctermbg=023
" do not underline error/info/hit lines
highlight! link CocErrorHighlight NoCocUnderline
highlight! link CocWarningHighlight NoCocUnderline
highlight! link CocInfoHighlight NoCocUnderline
highlight! link CocHintHighlight NoCocUnderline

augroup coc_au
  autocmd!
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  autocmd User CocQuickfixChange :CocList --normal quickfix
  autocmd CursorHold * silent call CocActionAsync('highlight')
  autocmd CompleteDone * if pumvisible() == 0 | pclose | endif
augroup END
'''
