[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = ['BufReadPre', 'BufNewFile']
hook_source = 'lua require("lb.config.vim-cursorword")'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Glog', 'Gdiff', 'Gstatus', 'Git!', 'Grebase', 'Gpull']

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'junegunn/vim-slash'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = ['FloatermNew', 'FloatermToggle', 'FloatermPrev', 'FloatermNext', 'FloatermSend', 'FloatermKill']
hook_source = 'lua require("lb.config.vim-floaterm")'

[[plugins]]
repo = 'simnalamburt/vim-mundo'
on_cmd = 'MundoToggle'
on_source = '''
set undofile
set undodir=$HOME/.vim/.cache/undo
let g:mundo_width = 50
let g:mundo_preview_height = 30
let g:mundo_right = 1
'''

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_source = '''
let g:asyncrun_open = 25
let g:asyncrun_bell = 1
let g:asyncrun_rootmarks = ['.svn', '.git', '.root', '_darcs', 'build.xml']
'''

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
depends = 'asyncrun.vim'
hook_source = '''
let g:asynctasks_term_pos = 'right'
let g:asynctasks_term_reuse = 0
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista', 'Vista!', 'Vista!!']
hook_source = 'lua require("lb.config.vista")'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_source = 'lua require("lb.config.nvim-telescope")'

[[plugins]]
repo = 'brooth/far.vim'
on_cmd = ['Far', 'Fardo', 'Farundo', 'F', 'Farr']

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tyru/caw.vim'
depends = ['vim-operator-user']
on_map = { 'nx' = '<Plug>' }
hook_source = '''
let g:caw_operator_keymappings = 0
'''

[[plugins]]
repo = 'matze/vim-move'
hook_source = '''
let g:move_key_modifier = 'C'
'''

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = ['StartupTime']

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_ft = ['vim', 'lua', 'html', 'css', 'sass', 'scss']
hook_source = '''
lua << EOF
require 'colorizer'.setup {
        css = { rgb_fn = true; };
        scss = { rgb_fn = true; };
        sass = { rgb_fn = true; };
        lua = { rgb_fn = true; };
        stylus = { rgb_fn = true; };
        vim = { names = true; };
        tmux = { names = false; };
        'javascript';
        'javascriptreact';
        'typescript';
        'typescriptreact';
        html = {
          mode = 'foreground';
        }
      }
EOF
'''
